apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livy.fullname" . }}-cm
  labels: {{- include "livy.labels" . | nindent 4 }}
data:
  {{- include "livy.configmap" . | nindent 2 }}
  {{- include "spark.configmap" . | nindent 2 }}
  {{- include "hadoop.configmap" . | nindent 2 }}
  {{- include "hive.configmap" . | nindent 2 }}
