apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datagram.fullname" . }}-cm
  labels: {{- include "datagram.labels" . | nindent 4 }}
data: {{- include "datagram.configmap" . | nindent 2 }}