{{- if not (empty .Values.postgresql.auth.password) }}
{{- $secret_name := (include "datagram.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datagram.fullname" . }}
  labels: {{- include "datagram.labels" . | nindent 4 }}
type: Opaque
data:
  postgresPassword: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- else }}
{{- fail "value for .Values.postgresql.auth.password is not set!\n\tPlease, define this variable in helm/datagram/values.yaml or set in runtime as '--set postgresql.auth.password=YOUR_PASSWORD_HERE' " }}
{{- end -}}
