apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-namenode-hdfs-0
  namespace: apache-hdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem