apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-namenode-hdfs-0
  annotations:
    pv.kubernetes.io/provisioned-by: deckhouse.io/localpath-deckhouse-system
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: apache-hdfs
    name: data-namenode-hdfs-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localpath-deckhouse-system
  hostPath:
    path: "/opt/local-path-provisioner/hdfs-namenode-0"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - deckhouse-02
