apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-namenode-hdfs-0
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hdfs
  annotations:
    meta.helm.sh/release-name: hdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem