apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.name" . }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: hive-thrift
      protocol: TCP
      name: hive-thrift
  
  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}
