apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJyZWdpc3RyeS5uZW9tc2EucnUvZG9ja2VyLW5lb2ZvdW5kYXRpb24iOnsidXNlcm5hbWUiOiJuZW9mb3VuZGF0aW9uLWFkbWluIiwicGFzc3dvcmQiOiJBU0xrbmtuYnVpdW9wMjg3MjdmZGJka25sS0pIV1VKV0hKIn19fQ==
type: kubernetes.io/dockerconfigjson
