{{- if .Values.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-spark-rolebinding
  labels:
    {{- include "spark-thrift.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-spark-role
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-thrift.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
{{- end }}
