kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "spark-history.name" . }}
data:
  spark-defaults.conf: |
    spark.history.fs.logDirectory={{ .Values.logPath }}
    {{- range .Values.extraSparkConfigs }}
    {{ . }}
    {{- end }}

