apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-console.fullname" . }}-cm
  labels: {{- include "admin-console.labels" . | nindent 4 }}
data: 
{{- range $key, $val := .Values.env }}
    {{ $key }}: {{ $val | quote }}
{{- end }}