{{- if not (empty .Values.postgresql.auth.password) }}
{{- $secret_name := (include "admin-console.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin-console.fullname" . }}-secret
  labels: {{- include "admin-console.labels" . | nindent 4 }}
type: Opaque
data:
  postgresPassword: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- range $key, $val := .Values.secretEnv}}
  {{ $key }}: {{ $val  | b64enc | quote }}
{{- end }}  
{{- else }}
{{- fail "value for .Values.postgresql.auth.password is not set!\n\tPlease, define this variable in helm/ac/values.yaml or set in runtime as '--set postgresql.auth.password=YOUR_PASSWORD_HERE' " }}
{{- end -}}
